version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g htmlhint stylelint

  pre_build:
    commands:
      - echo "Starting tests..."

  build:
    commands:
      - echo "Running HTML validation..."
      - htmlhint index.html || exit 1
      - echo "Running CSS validation..."
      - stylelint Styles.css || exit 1

  post_build:
    commands:
      - echo "Tests completed successfully!"
