version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g htmlhint stylelint

  pre_build:
    commands:
      - echo "Starting tests..."

  build:
    commands:
      - echo "Running HTML validation..."

  post_build:
    commands:
      - echo "Tests completed successfully!"
