version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g htmlhint

  pre_build:
    commands:
      - echo "Starting HTML validation test..."

  build:
    commands:
      - echo "Running HTML validation..."
      - htmlhint index.html || exit 1

  post_build:
    commands:
      - echo "HTML validation test completed successfully!"
